spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    serialization:
      write_dates_as_timestamps: false
    default-property-inclusion: non_null
    deserialization:
      accept_float_as_int: false
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    show-sql: true
    open-in-view: false
  messages:
    basename: messages.exception

  datasource:
    initial-size: 10
    max-active: 50
    max-wait: 1000
    min-idle: 10
    name: accounting
    test-on-borrow: true
    url: jdbc:mysql://localhost:3306/mock
    username: root
    password: 123456789
    validation-query: SELECT 1
  redis:
    database: 0
    pool:
      min-idle: 1
      max-idle: 4

server:
  port: 8888

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
  tools:
    schemaLocationPattern: "**/*.graphqls"
  datetime:
    scalars:
      offsetDateTime:
        format: yyyy-MM-dd HH:mm:ss