spring:
  application:
    name: springtest
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    serialization:
      write_dates_as_timestamps: false
    default-property-inclusion: non_null
    deserialization:
      accept_float_as_int: false
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    show-sql: true
    open-in-view: false
  messages:
    basename: messages.exception
  profiles:
    active: dev
server:
  port: 8888

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
  tools:
    schemaLocationPattern: "**/*.graphqls"
  datetime:
    scalars:
      offsetDateTime:
        format: yyyy-MM-dd HH:mm:ss